### ISSUE TITLE
Implement Timer Notification System

### ISSUE THREAD

**Issue by 404FoundMeX** [Dedakup/focusflow#29]
Because this is a critical feature for this application, it needs to be implemented. When the timer ends, a sound is played and a warning message is displayed.

**Comment by Omeshcoding** [comment]
how about we add a message like "Did you complete the task" and a cool "You have done well" message

**Comment by 404FoundMeX** [comment]
Yes, we can use the Notification API for messages about the end of a timer or break and material tailwind alert to ask if he has finished tasks and congratulations on the completion of a task

**Comment by Omeshcoding** [comment]
and we can add some alert notification like '1 mins remaining in your time-block'
